[DEFAULT]
ptsiem_sdk=/home/runner/xp-kbt/xp-sdk
build_tools=/home/runner/xp-kbt/build-tools
taxonomy=/home/runner/xp-kbt/knowledgebase/contracts/taxonomy/taxonomy.json
output_folder=/home/runner/temp/eXtractionAndProcessing/output/packages
GITHUB_WORKSPACE=/home/runner/work/open-xp-rules/open-xp-rules
temp=/home/runner/temp/eXtractionAndProcessing/output/packages

[make-nfgraph]
type=BUILD_RULES
rcc_lang=n
rules_src=${GITHUB_WORKSPACE}/packages
xp_appendix=/home/runner/xp-kbt/knowledgebase/contracts/xp_appendix/appendix.xp
out=${output_folder}/formulas_graph.json

[make-argraph]
type=BUILD_RULES
rcc_lang=a
rules_src=${GITHUB_WORKSPACE}/packages
out=${output_folder}/aggfilters.json

[make-tables-schema]
type=BUILD_TABLES_SCHEMA
table_list_schema_src=${GITHUB_WORKSPACE}/packages
contract=/home/runner/xp-kbt/knowledgebase/contracts/tabular_lists/tables_contract.yaml
out=${output_folder}

[make-tables-db]
type=BUILD_TABLES_DATABASE
table_list_filltype=All
table_list_schema=${output_folder}/schema.json
table_list_defaults=${output_folder}/correlation_defaults.json
out=${output_folder}/fpta_db.db

[make-ergraph]
type=BUILD_RULES
rcc_lang=e
rules_src=${GITHUB_WORKSPACE}/packages
rfilters_src=${GITHUB_WORKSPACE}/common/rules_filters
table_list_schema=${output_folder}/schema.json
out=${output_folder}/enrules_graph.json

[make-crgraph]
type=BUILD_RULES
rcc_lang=c
rules_src=${GITHUB_WORKSPACE}/packages/windows_open_package/correlation_rules/mitre_attck_cred_access/KeePass_CredDump
rfilters_src=${GITHUB_WORKSPACE}/common/rules_filters
table_list_schema=${output_folder}/schema.json
out=${output_folder}/corrules_graph.json

[rules-tests]
type=TEST_RULES
cr_timeout=250
formulas=${output_folder}/formulas_graph.json
enrules=${output_folder}/enrules_graph.json
corrules=${output_folder}/corrules_graph.json
aggrules=${output_folder}/aggfilters.json
table_list_defaults=${output_folder}/correlation_defaults.json
rules_src=${GITHUB_WORKSPACE}/packages/windows_open_package/correlation_rules/mitre_attck_cred_access/KeePass_CredDump
temp=/home/runner/temp/eXtractionAndProcessing/output/09d84b4f-d422-a57f-a46f-135eb7d12719
keep_temp_files=yes

[main]
type=SCENARIO
scenario=make-argraph make-tables-schema make-tables-db make-ergraph make-crgraph rules-tests
