[DEFAULT]
ptsiem_sdk=/home/runner/xp-kbt/xp-sdk
build_tools=/home/runner/xp-kbt/build-tools
taxonomy=/home/runner/xp-kbt/knowledgebase/contracts/taxonomy/taxonomy.json
output_folder=/home/runner/xp-kbt/Temp/eXtractionAndProcessing/output/packages
temp=/home/runner/xp-kbt/Temp/eXtractionAndProcessing/output/packages
[make-nfgraph]
type=BUILD_RULES
rcc_lang=n
rules_src=packages
xp_appendix=/home/runner/knowledgebase/contracts/xp_appendix/appendix.xp
out=${output_folder}/formulas_graph.json
[make-argraph]
type=BUILD_RULES
rcc_lang=a
rules_src=packages
out=${output_folder}/aggfilters.json
[make-tables-schema]
type=BUILD_TABLES_SCHEMA
table_list_schema_src=packages
contract=/home/runner/xp-kbt/knowledgebase/contracts/tabular_lists/tables_contract.yaml
out=${output_folder}
[make-tables-db]
type=BUILD_TABLES_DATABASE
table_list_filltype=All
table_list_schema=${output_folder}/schema.json
table_list_defaults=${output_folder}/correlation_defaults.json
out=${output_folder}/fpta_db.db
[make-ergraph]
type=BUILD_RULES
rcc_lang=e
rules_src=packages
rfilters_src=common/rules_filters
table_list_schema=${output_folder}/schema.json
out=${output_folder}/enrules_graph.json
[make-crgraph]
type=BUILD_RULES
rcc_lang=c
rules_src=packages
rfilters_src=common/rules_filters
table_list_schema=${output_folder}/schema.json
out=${output_folder}/corrules_graph.json
[rules-tests]
type=TEST_RULES
cr_timeout=250
formulas=${output_folder}/formulas_graph.json
enrules=${output_folder}/enrules_graph.json
corrules=${output_folder}/corrules_graph.json
aggrules=${output_folder}/aggfilters.json
table_list_defaults=${output_folder}/correlation_defaults.json
rules_src=packages
temp=/home/runner/xp-kbt/Temp/eXtractionAndProcessing/output
keep_temp_files=no
[main]
type=SCENARIO
scenario=make-nfgraph make-argraph make-tables-schema make-tables-db make-ergraph make-crgraph rules-tests
