name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_YAML: true

  integration_tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar

      - name: Download and extract xp-kbt
        run: |
          KBT_VERSION="27.0.78"
          wget https://github.com/vxcontrol/xp-kbt/releases/download/${KBT_VERSION}/kbt.${KBT_VERSION}-linux.tar.gz -O /home/runner/xp-kbt.tar.gz
          mkdir -p /home/runner/xp-kbt && tar -xzvf /home/runner/xp-kbt.tar.gz -C /home/runner/xp-kbt

      - name: Prepare environment
        run: mkdir -p /home/runner/temp/eXtractionAndProcessing/output/packages

      - name: Run integration tests
        run: /home/runner/xp-kbt/extra-tools/siemj/siemj -c .github/workflows/siemj.conf main

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /home/runner/temp/eXtractionAndProcessing/output/packages

  release:
    needs: integration_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Semantic Release
        run: npm install -g semantic-release

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
