name: Dev Container Build and Test 2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: .devcontainer/devcontainer.json

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Cache xp-kbt archive
      uses: actions/cache@v3
      with:
        path: /home/runner/xp-kbt
        key: ${{ runner.os }}-xp-kbt-${{ hashFiles('xp-kbt.tar.gz') }}
        restore-keys: |
          ${{ runner.os }}-xp-kbt-

    - name: Download and Extract xp-kbt
      run: |
        KBT_VERSION="27.0.78"
        KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${KBT_VERSION}/kbt.${KBT_VERSION}-linux.tar.gz"
        mkdir -p /home/runner/xp-kbt
        wget -q $KBT_URL -O - | sudo tar --no-same-owner -xz -C /home/runner/xp-kbt

    - name: Create required directories
      run: |
        mkdir -p /home/runner/temp/eXtractionAndProcessing/output/packages

    - name: Corr rule test with better logs
      run: |
        mkdir -p logs
        /home/runner/xp-kbt/extra-tools/siemj/siemj -c siemj.conf main > logs/test_output.log 2>&1

    - name: Count warnings and errors
      run: |
        warnings=$(grep -i "warning" logs/test_output.log | wc -l)
        errors=$(grep -i "error" logs/test_output.log | wc -l)
        passed_tests=$(grep -o 'All tests OK' test-log.txt | wc -l)
        echo "$passed_tests tests passed"
        echo "Total warnings: $warnings"
        echo "Total errors: $errors"

    - name: Upload logs to GitHub artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: logs/test_output.log
