name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update package list and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar

    - name: Download xp-kbt archive
      run: |
        KBT_VERSION="27.0.78"
        KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${KBT_VERSION}/kbt.${KBT_VERSION}-linux.tar.gz"
        wget $KBT_URL -O /home/runner/xp-kbt.tar.gz

    - name: Extract xp-kbt archive
      run: |
        mkdir -p /home/runner/xp-kbt
        tar -xzvf /home/runner/xp-kbt.tar.gz -C /home/runner/xp-kbt

    - name: Create required directories
      run: |
        mkdir -p /home/runner/temp/eXtractionAndProcessing/output/packages

    - name: Run tests
      run: |
        /home/runner/xp-kbt/extra-tools/siemj/siemj -c .github/workflows/siemj.conf main

    - name: Run cleanup script
      run: |
        chmod +x ./scripts/cleanup.sh
        ./scripts/cleanup.sh $GITHUB_WORKSPACE

    - name: Install .NET SDK
      run: |
        sudo apt-get install -y dotnet-sdk-6.0

    - name: Create new release using kbtpack.dll
      run: |
        ls -la /home/runner/xp-kbt
        echo "!!!"
        ls -la /home/runner/xp-kbt/temp/eXtractionAndProcessing/output
        dotnet /home/runner/xp-kbt/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o /home/runner/temp/eXtractionAndProcessing/output/packages/out
        echo "!!!!!!"
        ls -la /home/runner/temp/eXtractionAndProcessing/output/packages/out
    - name: List files after running kbtpack.dll
      run: |
        ls -la /home/runner/temp/eXtractionAndProcessing/output/packages