name: Release Current Version

on:
  workflow_dispatch:

jobs:
    setup:
        name: Setup Current Version
        uses: ./.github/workflows/setup_kbt.yml
        with:
            kbt_version: "27.0.78"

    test:
        name: Test Current Version
        runs-on: ubuntu-latest
        needs: setup
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
          - name: Restore Cache
            uses: actions/cache@v3
            with:
                path: |
                    /home/runner/xp-kbt
                    /home/runner/temp/eXtractionAndProcessing/output/packages
                key: setup-kbt-stable

          - name: Run Tests
            run: |
                /home/runner/xp-kbt/extra-tools/siemj/siemj -c .github/config/siemj.conf main

    package_full:
        name: Package Full - Current Version
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Restore Cache
            uses: actions/cache@v3
            with:
                path: |
                    /home/runner/xp-kbt
                    /home/runner/temp/eXtractionAndProcessing/output/packages
                key: setup-kbt-stable

          - name: Pack Full Content
            run: |
                dotnet /home/runner/xp-kbt/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o /home/runner/temp/eXtractionAndProcessing/output/packages/pack.full.current.kb

    package_open:
        name: Package Open - Current Version
        runs-on: ubuntu-latest
        needs: package_full
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Restore Cache
            uses: actions/cache@v3
            with:
                path: |
                    /home/runner/xp-kbt
                    /home/runner/temp/eXtractionAndProcessing/output/packages
                key: setup-kbt-stable

          - name: Filter System Content
            run: chmod +x ./.github/scripts/filter_open_content.sh $GITHUB_WORKSPACE

          - name: Pack Open Content
            run: |
                dotnet /home/runner/xp-kbt/extra-tools/kbpack/kbpack.dll pack -s $GITHUB_WORKSPACE -o /home/runner/temp/eXtractionAndProcessing/output/packages/pack.open.current.kb
                ls /home/runner/temp/eXtractionAndProcessing/output/packages/pack.open.current.kb
    release:
        name: Release Packages - Current Version
        runs-on: ubuntu-latest
        needs: [package_full, package_open]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Restore Cache
            uses: actions/cache@v3
            with:
                path: |
                    /home/runner/xp-kbt
                    /home/runner/temp/eXtractionAndProcessing/output/packages
                key: setup-kbt-stable
          
          - name: Upload Full Current Package as Artifact
            uses: actions/upload-artifact@v3
            with:
                name: pack-full-current-kb
                path: /home/runner/temp/eXtractionAndProcessing/output/packages/pack.full.current.kb
        
          - name: Upload Open Current Package as Artifact
            uses: actions/upload-artifact@v3
            with:
                name: pack-open-current-kb
                path: /home/runner/temp/eXtractionAndProcessing/output/packages/pack.open.current.kb
