name: Setup xp-kbt

on:
    workflow_call:
        inputs:
            kbt_version:
                required: true
                type: string

jobs:
    setup_kbt:
        runs-on: ubuntu-latest
        steps:
          - name: Install dependencies
            run: |
                sudo apt-get update
                sudo apt-get install -y wget tar dotnet-sdk-8.0

          - name: Download KBT
            run: |
                KBT_URL="https://github.com/vxcontrol/xp-kbt/releases/download/${{ inputs.kbt_version }}/kbt.${{ inputs.kbt_version }}-linux.tar.gz"
                wget $KBT_URL -O /home/runner/xp-kbt.tar.gz
            continue-on-error: true

          - name: Extract KBT
            run: |
                mkdir -p /home/runner/xp-kbt
                tar -xzvf /home/runner/xp-kbt.tar.gz -C /home/runner/xp-kbt

          - name: Create required directories
            run: |
                mkdir -p /home/runner/temp/eXtractionAndProcessing/output/packages

          - name: Cache Setup Output
            uses: actions/cache@v3
            with:
                path: /
                key: setup-kbt-stable