name: Dev Container Build and Test

on:
    workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

      - name: Create directory for xp-kbt
        run: mkdir -p /home/runner/xp-kbt

      - name: Download and extract xp-kbt
        run: |
          wget $(curl -s https://api.github.com/repos/vxcontrol/xp-kbt/releases/latest | jq -r '.assets[] | select(.name | contains("debian")).browser_download_url') -O /home/runner/xp-kbt.zip
          unzip -o /home/runner/xp-kbt.zip -d /home/runner/xp-kbt
